name: Conformance Testsuite

on:
  push:
    paths:
    - '.github/workflows/testsuite.yml'
    - 'test/**'
    - '!test/README.md'
  pull_request:
    paths:
    - '.github/workflows/testsuite.yml'
    - 'test/**'
    - '!test/README.md'

jobs:
  build-adapter-substrate:
    name: Build substrate adapter
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup rust toolchain
      id: rustup
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly-2020-04-15
        target: wasm32-unknown-unknown
        default: true
        profile: minimal
    - name: Cache cargo registry
      uses: actions/cache@v1
      with:
        path: ~/.cargo/registry
        key: cargo-registry-adapter-substrate-${{ hashFiles('test/adapters/substrate/Cargo.lock') }}
        restore-key: cargo-registry-adapter-substrate-
    - name: Cache cargo index
      uses: actions/cache@v1
      with:
        path: ~/.cargo/git
        key: cargo-index-adapter-substrate-${{ hashFiles('test/adapters/substrate/Cargo.lock') }}
        restore-key: cargo-index-adapter-substrate-
    - name: Cache cargo build
      uses: actions/cache@v1
      with:
        path: test/adapters/substrate/target
        key: cargo-build-adapter-substrate-${{ steps.rustup.outputs.rustc_hash }}-${{ hashFiles('test/adapters/substrate/Cargo.lock') }}
        restore-keys: cargo-build-adapter-substrate-${{ steps.rustup.outputs.rustc_hash }}-
    - name: Build substrate adapters
      working-directory: test/adapters/substrate
      run: cargo build --release
    - name: Upload substrate adapter
      uses: actions/upload-artifact@v1
      with:
        name: substrate-adapter
        path: test/adapters/substrate/target/release/substrate-adapter
    - name: Upload substrate legacy adapter
      uses: actions/upload-artifact@v1
      with:
        name: substrate-adapter-legacy
        path: test/adapters/substrate/target/release/substrate-adapter-legacy

  build-adapter-kagome:
    name: Build kagome adapter
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Cache hunter packages
      uses: actions/cache@v1
      with:
        path: ~/.hunter
        key: hunter-adapter-kagome-${{ hashFiles('test/adapters/kagome/CMakeLists.txt') }}
        restore-key: hunter-adapter-kagome-
    - name: Build kagome adapter
      working-directory: test/adapters/kagome
      env:
        CC: gcc-9
        CXX: g++-9
      run: |
        cmake -DCMAKE_BUILD_TYPE=Release -B build -S .
        cmake --build build
    - name: Upload kagome adapter
      uses: actions/upload-artifact@v1
      with:
        name: kagome-adapter
        path: test/adapters/kagome/build/kagome-adapter

  build-adapter-gossamer:
    name: Build gossamer adapter
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: test/adapters/gossamer
    steps:
    - uses: actions/checkout@v2
    - name: Cache go modules
      uses: actions/cache@v1
      with:
        path: ~/go/pkg/mod
        key: go-mod-adapter-gossamer-${{ hashFiles('test/adapters/gossamer/go.sum') }}
        restore-key: go-mod-adapter-gossamer-
    - name: Build gossamer adapter
      run: go build
    - name: Upload gossamer adapter
      uses: actions/upload-artifact@v1
      with:
        name: gossamer-adapter
        path: test/adapters/gossamer/gossamer-adapter


  test-kagome:
    needs: [ build-adapter-substrate, build-adapter-kagome ]
    strategy:
      fail-fast: false
      matrix:
        fixture: [ scale-codec, state-trie ]
    name: Test kagome against ${{ matrix.fixture }} fixture
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v1
      with:
        name: substrate-adapter
        path: test/adapters/substrate
    - uses: actions/download-artifact@v1
      with:
        name: kagome-adapter
        path: test/adapters/kagome
    - run: cd test/adapters && chmod +x substrate/substrate-adapter kagome/kagome-adapter
    - name: Run test fixture
      run: test/check.jl kagome ${{ matrix.fixture }}

  test-gossamer:
    needs: [ build-adapter-substrate, build-adapter-gossamer ]
    strategy:
      fail-fast: false
      matrix:
        fixture: [ scale-codec, state-trie ]
    name: Test gossamer against ${{ matrix.fixture }} fixture
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v1
      with:
        name: substrate-adapter
        path: test/adapters/substrate
    - uses: actions/download-artifact@v1
      with:
        name: gossamer-adapter
        path: test/adapters/gossamer
    - run: cd test/adapters && chmod +x substrate/substrate-adapter gossamer/gossamer-adapter
    - name: Run test fixture
      run: test/check.jl gossamer ${{ matrix.fixture }}

  test-substrate:
    needs: build-adapter-substrate
    name: Test substrate against hostapi fixture
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v1
      with:
        name: substrate-adapter
        path: test/adapters/substrate
    - run: chmod +x test/adapters/substrate/substrate-adapter
    - name: Run test fixture
      run: test/check.jl substrate hostapi


  test-hostapi-legacy:
    needs: [ build-adapter-substrate, build-adapter-kagome ]
    strategy:
      fail-fast: false
      matrix:
        implementation: [ substrate, kagome ]
    name: Test ${{ matrix.implementation }} against hostapi-legacy fixture
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v1
      with:
        name: ${{ matrix.implementation }}-adapter-legacy
        path: test/adapters/${{ matrix.implementation }}
      if: matrix.implementation == 'substrate'
    - uses: actions/download-artifact@v1
      with:
        name: ${{ matrix.implementation }}-adapter
        path: test/adapters/${{ matrix.implementation }}
      if: matrix.implementation == 'kagome'
    - run: chmod +x test/adapters/substrate/substrate-adapter-legacy
      if: matrix.implementation == 'substrate'
    - run: chmod +x test/adapters/kagome/kagome-adapter
      if: matrix.implementation == 'kagome'
    - name: Run test fixture
      run: test/check.jl ${{ matrix.implementation }} hostapi-legacy

