name: Conformance Testsuite

on:
  push:
    paths:
    - '.github/workflows/testsuite.yml'
    - 'test/**'
    - '!test/testers/**'
    - '!test/README.md'
  pull_request:
    paths:
    - '.github/workflows/testsuite.yml'
    - 'test/**'
    - '!test/testers/**'
    - '!test/README.md'

jobs:
  build-adapter-substrate:
    name: "[build] substrate-adapter"
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Setup rust toolchain
      id: rustup
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly-2020-04-15
        target: wasm32-unknown-unknown
        default: true
        profile: minimal
    - name: Cache cargo registry
      uses: actions/cache@v1
      with:
        path: ~/.cargo/registry
        key: cargo-registry-adapter-substrate-${{ hashFiles('test/adapters/substrate/Cargo.lock') }}
        restore-keys: cargo-registry-adapter-substrate-
    - name: Cache cargo index
      uses: actions/cache@v1
      with:
        path: ~/.cargo/git
        key: cargo-index-adapter-substrate-${{ hashFiles('test/adapters/substrate/Cargo.lock') }}
        restore-keys: cargo-index-adapter-substrate-
    - name: Cache cargo build ouput
      uses: actions/cache@v1
      with:
        path: test/adapters/substrate/target
        key: cargo-build-adapter-substrate-${{ steps.rustup.outputs.rustc_hash }}-${{ hashFiles('test/adapters/substrate/Cargo.lock') }}
        restore-keys: cargo-build-adapter-substrate-${{ steps.rustup.outputs.rustc_hash }}-
    - name: Build substrate adapters
      working-directory: test/adapters/substrate
      run: cargo build --release
    - name: Upload substrate adapter
      uses: actions/upload-artifact@v1
      with:
        name: substrate-adapter
        path: test/adapters/substrate/target/release/substrate-adapter

  build-adapter-substrate-legacy:
    name: "[build] substrate-adapter-legacy"
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Setup rust toolchain
      id: rustup
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly-2020-04-15
        target: wasm32-unknown-unknown
        default: true
        profile: minimal
    - name: Cache cargo registry
      uses: actions/cache@v1
      with:
        path: ~/.cargo/registry
        key: cargo-registry-adapter-substrate-legacy-${{ hashFiles('test/adapters/substrate-legacy/Cargo.lock') }}
        restore-keys: cargo-registry-adapter-substrate-legacy-
    - name: Cache cargo index
      uses: actions/cache@v1
      with:
        path: ~/.cargo/git
        key: cargo-index-adapter-substrate-legacy-${{ hashFiles('test/adapters/substrate-legacy/Cargo.lock') }}
        restore-keys: cargo-index-adapter-substrate-legacy-
    - name: Cache cargo build output
      uses: actions/cache@v1
      with:
        path: test/adapters/substrate-legacy/target
        key: cargo-build-adapter-substrate-legacy-${{ steps.rustup.outputs.rustc_hash }}-${{ hashFiles('test/adapters/substrate-legacy/Cargo.lock') }}
        restore-keys: cargo-build-adapter-substrate-legacy-${{ steps.rustup.outputs.rustc_hash }}-
    - name: Build substrate legacy adapters
      working-directory: test/adapters/substrate-legacy
      run: cargo build --release
    - name: Upload substrate legacy adapter
      uses: actions/upload-artifact@v1
      with:
        name: substrate-adapter-legacy
        path: test/adapters/substrate-legacy/target/release/substrate-adapter-legacy

  build-adapter-kagome:
    name: "[build] kagome-adapter"
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Cache hunter packages
      uses: actions/cache@v1
      with:
        path: ~/.hunter
        key: hunter-adapter-kagome-${{ hashFiles('test/adapters/kagome/CMakeLists.txt') }}
        restore-keys: hunter-adapter-kagome-
    - name: Build kagome adapter
      working-directory: test/adapters/kagome
      env:
        CC: gcc-9
        CXX: g++-9
      run: |
        cmake -DCMAKE_BUILD_TYPE=Release -B build -S .
        cmake --build build
    - name: Upload kagome adapter
      uses: actions/upload-artifact@v1
      with:
        name: kagome-adapter
        path: test/adapters/kagome/build/kagome-adapter

  build-adapter-gossamer:
    name: "[build] gossamer-adapter"
    runs-on: ubuntu-18.04
    defaults:
      run:
        working-directory: test/adapters/gossamer
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Cache go modules
      uses: actions/cache@v1
      with:
        path: ~/go/pkg/mod
        key: go-mod-adapter-gossamer-${{ hashFiles('test/adapters/gossamer/go.sum') }}
        restore-keys: go-mod-adapter-gossamer-
    - name: Build gossamer adapter
      run: go build
    - name: Upload gossamer adapter
      uses: actions/upload-artifact@v1
      with:
        name: gossamer-adapter
        path: test/adapters/gossamer/gossamer-adapter


  test-substrate:
    needs: build-adapter-substrate
    name: "[test-host-api] substrate"
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - uses: actions/download-artifact@v1
      with:
        name: substrate-adapter
        path: test/adapters/substrate
    - run: chmod +x test/adapters/substrate/substrate-adapter
    - name: Run test fixture
      run: test/runtests.jl substrate host-api

  test-kagome:
    needs: [ build-adapter-substrate, build-adapter-kagome ]
    strategy:
      fail-fast: false
      matrix:
        fixture: [ scale-codec, state-trie ]
    name: "[test-${{ matrix.fixture }}] kagome"
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - uses: actions/download-artifact@v1
      with:
        name: substrate-adapter
        path: test/adapters/substrate
    - uses: actions/download-artifact@v1
      with:
        name: kagome-adapter
        path: test/adapters/kagome
    - run: cd test/adapters && chmod +x substrate/substrate-adapter kagome/kagome-adapter
    - name: Run test fixture
      run: test/runtests.jl kagome ${{ matrix.fixture }}

  test-gossamer:
    needs: [ build-adapter-substrate, build-adapter-gossamer ]
    strategy:
      fail-fast: false
      matrix:
        fixture: [ scale-codec, state-trie ]
    name: "[test-${{ matrix.fixture }}] gossamer"
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - uses: actions/download-artifact@v1
      with:
        name: substrate-adapter
        path: test/adapters/substrate
    - uses: actions/download-artifact@v1
      with:
        name: gossamer-adapter
        path: test/adapters/gossamer
    - run: cd test/adapters && chmod +x substrate/substrate-adapter gossamer/gossamer-adapter
    - name: Run test fixture
      run: test/runtests.jl gossamer ${{ matrix.fixture }}


  test-host-api-legacy:
    needs: [ build-adapter-substrate-legacy, build-adapter-kagome ]
    strategy:
      fail-fast: false
      matrix:
        implementation: [ substrate, kagome ]
    name: "[test-host-api-legacy] ${{ matrix.implementation }}"
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - uses: actions/download-artifact@v1
      with:
        name: ${{ matrix.implementation }}-adapter-legacy
        path: test/adapters/${{ matrix.implementation }}-legacy
      if: matrix.implementation == 'substrate'
    - uses: actions/download-artifact@v1
      with:
        name: ${{ matrix.implementation }}-adapter
        path: test/adapters/${{ matrix.implementation }}
      if: matrix.implementation == 'kagome'
    - run: chmod +x test/adapters/substrate-legacy/substrate-adapter-legacy
      if: matrix.implementation == 'substrate'
    - run: chmod +x test/adapters/kagome/kagome-adapter
      if: matrix.implementation == 'kagome'
    - name: Run test fixture
      run: test/runtests.jl ${{ matrix.implementation }} host-api-legacy

